# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: n-wbrown's website
email: n-wbrown@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://n-wbrown.github.io/"
github_username:  n-wbrown
assets_path: 

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed
  load_paths:
    - _sass
#    - assets/vendor/bootstrap-5.0.0-beta2/scss

collections:
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: 
  # Bootstrap
  - assets/vendor/bootstrap-5.0.0-beta2/build
  - assets/vendor/bootstrap-5.0.0-beta2/nuget
  - assets/vendor/bootstrap-5.0.0-beta2/site
  - assets/vendor/bootstrap-5.0.0-beta2/CODE_OF_CONDUCT.md
  - assets/vendor/bootstrap-5.0.0-beta2/LICENSE
  - assets/vendor/bootstrap-5.0.0-beta2/README.md
  - assets/vendor/bootstrap-5.0.0-beta2/SECURITY.md
  - assets/vendor/bootstrap-5.0.0-beta2/composer.json
  - assets/vendor/bootstrap-5.0.0-beta2/config.yml
  - assets/vendor/bootstrap-5.0.0-beta2/package-lock.json
  - assets/vendor/bootstrap-5.0.0-beta2/package*
